[package]
name = "chat-rpg"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.6"
